title: Austin C. Zeller
description: Wildlife biologist, quantitative ecologist, and creative based in Whitehorse, Yukon.
url: https://austinczeller.github.io
baseurl: ""

author:
  name: Austin C. Zeller
  email: azeller@ualberta.ca
  github: https://github.com/austinczeller
  scholar: https://scholar.google.ca/citations?user=YCjBS-sAAAAJ&hl=en
  linkedin: https://www.linkedin.com/in/austin-zeller-707741162/
